# Generated by Django 5.0.9 on 2025-10-15 20:26

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text="Tenant name (e.g., 'School 1')", max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('paid_until', models.DateField(blank=True, help_text='Subscription end date', null=True)),
                ('on_trial', models.BooleanField(default=True, help_text='Is this tenant on trial?')),
            ],
            options={
                'db_table': 'tenants_client',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.client')),
            ],
            options={
                'db_table': 'tenants_domain',
            },
        ),
    ]
